### ISSUE TITLE
differential expression table between groups

### ISSUE THREAD

**Issue by KateK** [pmoulos/metaseqR2-local#14] opened 2021-07-16 12:57 UTC
Hi!

Within http report there is only an option to view and filter 10% of the best genes. Can I easily get whole table consisting normalized data, logFC, and pval? I see that there is an option to generate a table with all deg genes, but in this table there are some values with comma in chromosome column and there is no gene id to identify row of interest. 

Thanks in advance!
Kate

**Comment by KateK** [comment] 2021-07-16 13:16
Ok, I see that I can view table with up/down reg genes after volcanoplot, but it seems to have some errors due to fe number in column with gene name. Also, I would prefer table as in results, but with all genes

**Comment by pmoulos** [comment] 2021-07-16 13:33
Hi @KateK,

Normally, below the **Results** table, there are links to download the DEG genes as well as **all** genes with the metrics selected by the `exportWhat`, `exportValues` and `exportStats` options. This looks like below:

![image](https://user-images.githubusercontent.com/2979517/125955820-511aac6a-1183-44fc-9335-a068077c68b2.png)

There is a possibility that you can't see these because of a misrendered table. If this is the case, can you hide a long column using the *Show/Hide Columns* button and check if this is fixed? If this is the case I can see how can I fix misrendering issues...

In any case, if you are running locally, the respective lists are located in the `REPORT_FOLDER/lists` directory.

Best

**Comment by pmoulos** [comment] 2021-07-26 15:33
Hi @KateK,
Have you manage to navigate through the report? Are there more problems related to this issue?
If no I would like to close it.
Thank you in advance.

**Comment by KateK** [comment] 2021-07-26 16:09
Hi @pmoulos !
I am sorry for late reply, I have my days out of office. Yes, I found files in list folder and also links related to them in the report, but the problem is that this file looks like so:
<img width="1440" alt="Zrzut ekranu 2021-07-26 o 18 07 53" src="https://user-images.githubusercontent.com/5678468/127022061-2e9d5bf5-fcbb-4336-877c-b6f7b226ee10.png">

As you can see in the column chromosome I see some values that don't seem to represent chromosomes. Also, I don't see any column to know what gene expression fold change I see in each row...

**Comment by pmoulos** [comment] 2021-07-27 05:09
Hi @KateK,

This looks strange...
Can you post the command that you have used to generate the report/files as well as whether you are starting from BAM files or an already precalculated count matrix?

Thanks.

**Comment by KateK** [comment] 2021-07-27 11:23
Hi @pmoulos !

This is my command:

```
result <- metaseqr2(
  counts=countData,
  sampleList=sampleList,
  contrast=c("Quad_DM2_vs_Quad_Control","Heart_DM2_vs_Heart_Control", "Gastroc_DM2_vs_Tibialis_Control"),
  org="hg38",
  countType="gene",
  transLevel = "gene",
  normalization=c("noiseq"),
  statistics=c("noiseq"),
  pcut=0.05,
  figFormat="tiff",
  qcPlots=c("mds", "saturation", "readnoise","filtered", 
            "correl", "pairwise", "boxplot", "gcbias", 
            "lengthbias", "meandiff", "meanvar", "rnacomp", 
            "deheatmap", "volcano", "biodist", "mastat", 
            "statvenn", "foldvenn", "deregulogram"),
  exportWhat=c("p_value","adj_p_value","fold_change", "counts", "stats"),
  exportScale="natural",
  exportCountsTable = TRUE,
  exportValues=c("raw", "normalized"),
  exportStats="mean",
  exportWhere=file.path("~/Documents","PK_DM2_noiseq"),
  restrictCores=0.1,
  outList=TRUE
)

```

I used calculated count matrix generated by stringtie like so:
<img width="1440" alt="Zrzut ekranu 2021-07-27 o 13 22 33" src="https://user-images.githubusercontent.com/5678468/127145705-fa06e6e9-e630-4cce-9854-9e13587642f6.png">

Thanks for helping!

**Comment by pmoulos** [comment] 2021-07-27 17:24
Hi @KateK,

Thanks for the details. I think the problem is located at 
```
...
exportWhat=c("p_value","adj_p_value","fold_change", "counts", "stats"),
...
```

To be honest I never thought of exporting something without any annotation elements, so it's maybe a bug while collating the requested data columns to the final output. Until this is fixed, can you please add `annotation` to `exportWhat` and tell me if this fixes your problem?

That would be:

```
result <- metaseqr2(
  counts=countData,
  sampleList=sampleList,
  contrast=c("Quad_DM2_vs_Quad_Control","Heart_DM2_vs_Heart_Control", "Gastroc_DM2_vs_Tibialis_Control"),
  org="hg38",
  countType="gene",
  transLevel = "gene",
  normalization=c("noiseq"),
  statistics=c("noiseq"),
  pcut=0.05,
  figFormat="tiff",
  qcPlots=c("mds", "saturation", "readnoise","filtered", 
            "correl", "pairwise", "boxplot", "gcbias", 
            "lengthbias", "meandiff", "meanvar", "rnacomp", 
            "deheatmap", "volcano", "biodist", "mastat", 
            "statvenn", "foldvenn", "deregulogram"),
  exportWhat=c("annotation","p_value","adj_p_value","fold_change", "counts", "stats"),
  exportScale="natural",
  exportCountsTable = TRUE,
  exportValues=c("raw", "normalized"),
  exportStats="mean",
  exportWhere=file.path("~/Documents","PK_DM2_noiseq"),
  restrictCores=0.1,
  outList=TRUE
)
```

**Comment by KateK** [comment] 2021-07-27 18:29
Hello @pmoulos !

Thanks! To be honest I thought that annotation is exported automatically (sic!). Now the table looks normally. 

Thanks once again. You can close this topic.

Best,
Kate

**Closed as completed** 2021-07-27 18:33 UTC
