### ISSUE TITLE
count type

### ISSUE THREAD

**Issue by KateK** [pmoulos/metaseqR2-local#13] opened 2021-05-13 14:40 UTC
Hello, 

I think I have a problem with count table format. I read it as follows:`countData <- as.matrix(read.csv("gene_count_matrix_tab_names.csv", row.names="gene_id"))`

and than I extract only columns of interest: `dataMatrix <- countData[,7:19]`

than construct sample list: `sampleList <- list(Quad_DM2=colnames(countData)[19], Quad_Control=colnames(countData)[7:18])
`

And after calling `metaseqr2` function I got an error `Error in command 'file.exists (counts)': invalid argument 'file'`

My dataMatrix looks like (`head(dataMatrix[,1:5])`):

```
               Quad_Control_1 Quad_Control_10 Quad_Control_11 Quad_Control_12 Quad_Control_2
ENSG00000273423              4               1               1               2              1
ENSG00000212040              0               0               0               0              0
ENSG00000110514           1226            1206             517             693            747
ENSG00000086015           4017            4415            1496            2230           1936
ENSG00000211769              0               0               0               0              0
ENSG00000211768              0               0               0               1              0
```

Could you please help?

Regards,
Kate

**Comment by pmoulos** [comment] 2021-05-13 14:45
Hi @KateK,

Could you check if the problem is resolved if you provide a tab-delimited instead of csv file with the required columns directly to `metaseqr2`? If the problem is resolved like this then there is a potential bug.

Also, are you using the GitHub latest version or the current Bioconductor release version? Is it possible for you to post the complete command?

Thank you.

**Comment by KateK** [comment] 2021-05-14 12:13
Hi @pmoulos,

Yes, when I changed file to tab-delimited and read it with read.table the problem gone (`countData <- read.table("ene_count_matrix_tab_names.txt", row.names="gene_id", heade=TRUE, sep="\t")
)`

but right now I got an error `Loading gene annotation...Błąd w poleceniu '`.rowNamesDF<-`(x, value = value)':
  duplicate 'row.names' are not allowed` I think it's about annotation. Here is my code for `metaseqr2` function:

```
countData <- read.table("gene_count_matrix_tab_names.txt", row.names="gene_id", heade=TRUE, sep="\t")
colData <- read.csv("PHENO_DATA.txt", sep="\t", row.names=1)

dataMatrix <- countData[,7:19]
sampleList <- list(Quad_DM2=colnames(countData)[19], Quad_Control=colnames(countData)[7:18])

result <- metaseqr2(
  counts=dataMatrix,
  sampleList=sampleList,
  contrast=c("Quad_DM2_vs_Quad_Control"),
  annotation="embedded",
  org="hg38",
  countType="gene",
  transLevel = "gene",
  normalization="noiseq",
  statistics="noiseq",
  pcut=0.05,
  figFormat="png",
  qcPlots=c("mds","volcano"),
  exportWhat=c("p_value","adj_p_value","fold_change"),
  exportScale="natural",
  exportValues="normalized",
  exportStats="mean",
  exportWhere=file.path("~/Documents","test1"),
  restrictCores=0.1,
  outList=TRUE
)
```

I also post you whole error/warning message:

```
Additionally: Warning messages:
1: The column that contains the gene biotypes ("embedCols $ btCol") is missing with embedded annotation! Biotype filters and certain plots will not be available ...
2: non-unique values ​​when setting 'row.names': '0', '1', '10', '100', '1000', '1001', '1004', '1007', '101', '1011', '1012', '1014', '1015', '1016', '1018', '1019', '102', '1020', '1022', '1023', '1026', '103 ',' 1035 ',' 1036 ',' 1037 ',' 104 ',' 1041 ',' 1042 ',' 1043 ',' 1045 ',' 1049 ',' 105 ',' 1052 ',' 1053 ', '1056', '1057', '1059', '106', '1063', '1064', '1066', '1069', '107', '1071', '1074', '1077', '1079 ',' 108 ',' 1082 ',' 1083 ',' 1085 ',' 1089 ',' 109 ',' 1092 ',' 1093 ',' 1095 ',' 1098 ',' 11 ',' 110 ', '1100', '1105', '1106', '1107', '1108', '1109', '111', '1111', '1113', '1115', '1116', '1117', '1118 ',' 112 ',' 1124 ',' 1125 ',' 1126 ',' 1127 ',' 1128 ',' 113 ',' 1130 ',' 1132 ',' 1135
```

I've installed via devtools from GitHub 2 days ago.

Thanks!

**Comment by pmoulos** [comment] 2021-05-14 16:08
Hi @KateK,

In your command, can you change from `annotation="embedded"` to the default `annotation=NULL` or not provide this argument at all.
When `annotation="embedded"`, `metaseqr2` expects that the first 6-8 columns of the counts file contain BED file-like metadata like coordinates, gene names etc.

Let me know if this works.

**Comment by KateK** [comment] 2021-05-17 08:48
Hello @pmoulos,

Unfortunately no. When I removed/changed annotation argument I got an error as follows:

`error while computing argument 'x' selecting method for function 'intersect': object 'geneCounts' not found`

Also, I tried to check whether it works on trial data. I filtered them (`GC<-mm9GeneCounts[,9:12]`) and also got the same error.

Thanks for quick answer.

**Comment by pmoulos** [comment] 2021-05-17 11:39
Hi @KateK,

Can you check if the latest commit 80f2909 fixes the issue? I tested with the example data when providing as is (`annotation="embedded"), when providing as in your case as well as an external file.

Thanks.

**Comment by KateK** [comment] 2021-05-18 09:39
Hi @pmoulos,

It works. Thanks! I have one more question. I would like to perform nonparametric noiseq DEG analysis. In bioconductor tutorials they write about noiseq bio, and sim version. Is it possible to run it with metaseqR2  or I can ran only default version?

Thanks!
Kate

**Comment by pmoulos** [comment] 2021-05-18 14:19
Hi @KateK,

Thanks for letting me know.

In `metaseqr2` there is the `statArgs` argument which is a list you can use to pass custom arguments for each DE method you are using. The list members are named after the actual arguments in each DE function, apart from arguments that are used to separate methodology call such as in `noiseq`. So you are probably looking for the `replicates` argument in `statArgs` when it comes to NOISeq. To make myself more clear:

Use the `getDefaults` function to get the default arguments for NOISeq:

```
noiseqArgs <- getDefaults("statistics","noiseq")
```

You should get something like:

```
> getDefaults("statistics","noiseq")
$k
[1] 0.5

$norm
[1] "n"

$replicates
[1] "biological"

$factor
[1] "class"

$conditions
NULL

$pnr
[1] 0.2

$nss
[1] 5

$v
[1] 0.02

$lc
[1] 1

$nclust
[1] 15

$r
[1] 100

$adj
[1] 1.5

$a0per
[1] 0.9

$filter
[1] 0

$depth
NULL

$cv.cutoff
[1] 500

$cpm
[1] 1
```

You should notice that most list members are named after NOISeq function arguments. For example in `noiseqbio()` there is an argument called `norm` and another called `adj`. Their values are taken from this list. **And** there is also the `replicates` argument which you can use for your purpose. If `noiseqArgs$replicates` is `biological` (the default), `noiseqbio` is used, otherwise, `noiseqsim`.

So to make the long story short:

```
noiseqArgs <- getDefaults("statistics","noiseq")
noiseqArgs$replicates <- "YOUR_CHOICE"
noiseqArgs[["PARAM_YOU_WANT_TO_CHANGE"]] <- "PARAM_VALUE"

metaseqr2(
  ...,
  statistics="noiseq",
  statArgs=list(noiseq=noiseqArgs),
  ...
)
```

Hope this helps. However, please be extra careful as this functionality, although tested, it is not tested thoroughly enough. If it does not work as expected, please open another issue.

I am closing this one.

Best

**Closed as completed by pmoulos** 2021-05-18 14:19 UTC
Labels: bug
